#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SGWW.Resource", IsApplication=true)]

namespace SGWW
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ic_launcher_background = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int body = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int den_housetextutre = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int den_housetextutre2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int sgwwlogo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int texture1 = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int buttonDen = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int buttonKonstantin = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int buttonPublic = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int buttonRuslan = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int buttonSergek = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int buttonStas = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int buttonVitaly = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int buttonVladimir = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int sceneHolder = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_den = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_konstantin = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_public = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_ruslan = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_select = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_sergek = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_stas = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_vitaly = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_vladimir = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int den_fragment_shader = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int den_glass = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int den_glass_fragment_shader = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int den_glass_vertex_shader = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int den_house1_objnormal = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int den_house1_objtexture = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int den_house1_objvertex = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int den_house2_objnormal = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int den_house2_objtexture = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int den_house2_objvertex = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int den_house3_objnormal = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int den_house3_objtexture = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int den_house3_objvertex = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int den_vertex_shader = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int dolphin = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int dolphin2 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int fragment_line_shader = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int fragment_shader = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int fragment_shader2 = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int object1_objvertex = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int object2_objvertex = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int object3_objvertex = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int oldhouse_objnormal = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int oldhouse_objtexture = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int oldhouse_objvertex = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int one = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int simpleobj = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int vertex_line_shader = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int vertex_shader = 2130968604;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int action_settings = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
